### PR TITLE
Added install.sh and uninstall.sh

### PR DESCRIPTION
**Pull request by riteshsonawane1372**
Both installing and uninstalling are working fine 

``sh install.sh``
``sh uninstall.sh``

### CODE REVIEW

**Comment by surajnarwade** [comment]
What's the purpose of these scripts?

**Comment by riteshsonawane1372** [comment]
This script will install kubectl-eks

**Comment by riteshsonawane1372** [comment]
No this is not for user this is for us.

**Comment by surajnarwade** [comment]
@riteshsonawane1372 for developer references we already have Make commands, I would say instead of shell scripts, Make commands will be easier.

**Comment by riteshsonawane1372** [comment]
Okay

**Pull request closed without merging**
